name: Release
on:
  push:
    branches: 
      - master
    paths:
      - '.github/workflows/Release.yml'
      - '*.cs'
      - '*.csproj'
      - '*.sln'
env:
  release_tag: latest
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  Release:
    if: github.actor != 'github-actions'
    runs-on: windows-latest
    env:
      Project_Name: Pings
      Solution_Name: Pings.sln
      Release_Tag: latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.0.0
      with:
        versionSpec: '6.0.x'

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v3.0.0
      with:
        useConfigFile: true

    - name: Publish Windows Binaries
      run: dotnet publish ./${{ env.Project_Name }}.csproj -f net10.0-windows -r win-x64 -c Release --output ./

    - name: Compress binaries
      uses: crazy-max/ghaction-upx@v3
      with:
        version: latest
        args: --ultra-brute -k -o upx-${{ env.Project_Name }}.exe
        files: |
          ./${{ env.Project_Name }}.exe

    - name: Create Git tag And Push
      run: |
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
        git tag -a v${{ env.GitVersion_SemVer }} -m "Github Actions release ${{ env.GitVersion_SemVer }}"
        git push origin v${{ env.GitVersion_SemVer }}

    - run: gh release delete v${{ env.GitVersion_SemVer }} --cleanup-tag --yes
      continue-on-error: true

    - name: 发布版本存档
      run: gh release create v${{ env.GitVersion_SemVer }} ./${{ env.Project_Name }}.exe ./upx-${{ env.Project_Name }}.exe --target master --latest --title "${{ env.GitVersion_SemVer }}" --notes "v${{ env.GitVersion_SemVer }} ${{ github.sha }}"

    - run: gh release delete ${{ env.release_tag }} --cleanup-tag --yes
      continue-on-error: true

    - name: 发布正式版本
      run: gh release create ${{ env.release_tag }} ./${{ env.Project_Name }}.exe ./upx-${{ env.Project_Name }}.exe --target master --latest --title "${{ env.GitVersion_SemVer }}" --generate-notes
