name: Release
on:
  push:
    branches: 
      - master
    paths:
      - '*.cs'
      - '*.csproj'
      - '*.sln'
      - '*.yml'
jobs:
  build:
    if: github.actor != 'github-actions'
    strategy:
      matrix:
        configuration: [Release]
    runs-on: windows-latest
    env:
      Solution_Name: Pings.sln
      release_tag: latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Install GitVersion
      run: dotnet tool install -g GitVersion.Tool

    - name: Add GitVersion to PATH
      shell: bash
      run: echo "$(dotnet tool list -g | grep 'GitVersion.Tool' | awk '{print $4}')" >> $GITHUB_PATH

    - name: Use GitVersion
      id: gitversion
      run: dotnet-gitversion /output json /output buildserver
      env:
        GITVERSION_JSON: ${{ steps.gitversion.outputs.json }}

    - name: Extract GitVersion variables
      id: extract_variables
      run: |
        echo "GITVERSION_JSON=${{ steps.gitversion.outputs.json }}" >> $GITHUB_ENV
        echo "VERSION=$(echo ${{ steps.gitversion.outputs.json }} | jq -r .SemVer)" >> $GITHUB_ENV
        echo "ASSEMBLY_SEMVER=$(echo ${{ steps.gitversion.outputs.json }} | jq -r .AssemblySemVer)" >> $GITHUB_ENV
        echo "FILE_SEMVER=$(echo ${{ steps.gitversion.outputs.json }} | jq -r .FileSemVer)" >> $GITHUB_ENV
        echo "FULL_SEMVER=$(echo ${{ steps.gitversion.outputs.json }} | jq -r .FullSemVer)" >> $GITHUB_ENV
        echo "INFORMATIONAL_VERSION=$(echo ${{ steps.gitversion.outputs.json }} | jq -r .InformationalVersion)" >> $GITHUB_ENV
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release
    
    - name: Publish
      run: dotnet publish -r win-x64 -c Release --output ./publish
    
    - name: 发布新版本
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ env.release_tag }}"
        prerelease: false
        title: "${{ env.FILE_SEMVER }}"
        files: ./publish/Pings.exe
