name: Release
on:
  push:
    branches: 
      - master
    paths:
      - '*.cs'
      - '*.csproj'
      - '*.sln'
      - '*.yml'
      - '.github/workflows/*.yml'
jobs:
  build:
    if: github.actor != 'github-actions'
    strategy:
      matrix:
        configuration: [Release]
    runs-on: windows-latest
    env:
      Project_Name: Pings
      Solution_Name: Pings.sln
      Release_Tag: latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Debug Git Info
      run: |
        git fetch --all --tags
        git log --graph --oneline --all
        git tag

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Set git config
      run: |
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com

    - name: Install GitVersion
      run: dotnet tool install -g GitVersion.Tool

    - name: Add GitVersion to PATH
      run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

    - name: Use GitVersion
      id: gitversion
      run: dotnet-gitversion /output buildserver /config GitVersion.yml

    - name: Debug GitVersion
      run: gitversion /diag

    - name: Publish Windows Binaries
      run: dotnet publish ./${{ env.Project_Name }}.csproj -r win-x64 -c Release --output ./publish/

    - name: Create Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ env.Release_Tag }}"
        prerelease: false
        title: "${{ env.GitVersion_SemVer }}"
        files: ./publish/${{ env.Project_Name }}.exe