name: Release
on:
  push:
    branches: 
      - master
    paths:
      - '*.cs'
      - '*.csproj'
      - '*.sln'
      - '*.yml'
      - '.github/workflows/*.yml'
jobs:
  build:
    if: github.actor != 'github-actions'
    strategy:
      matrix:
        configuration: [Release]
    runs-on: windows-latest
    env:
      Solution_Name: Pings.sln
      Release_Tag: latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Install GitVersion
      run: dotnet tool install -g GitVersion.Tool

    - name: Add GitVersion to PATH
      run: echo "$(echo $env:GITVERSION_JSON)" >> $Env:GITHUB_PATH

    - name: Use GitVersion
      id: gitversion
      run: dotnet-gitversion /output json /output buildserver
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release
    
    - name: Publish
      run: dotnet publish -r win-x64 -c Release --output ./publish
    
    - name: Get GitVersion output
      id: gitversion-output
      run: |
        $version = dotnet-gitversion /output json | ConvertFrom-Json
        $semVer = $version.SemVer
        Write-Output "Build_Version=$semVer" >> $env:GITHUB_ENV

    - name: 发布新版本
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ env.Release_Tag }}"
        prerelease: false
        title: "Release ${{ env.Build_Version }}"
        files: ./publish/Pings.exe
